-- Supabase Schema for Precision Planning Module

CREATE TABLE crop_cycles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sowing_date DATE NOT NULL,
  crop_type TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE daily_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id BIGINT REFERENCES crop_cycles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pending', -- 'Pending', 'Completed', 'Rescheduled'
  task_date DATE NOT NULL,
  task_type TEXT NOT NULL, -- e.g., 'Irrigation', 'Fertilization', 'Harvesting', 'Inspection'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE soil_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nitrogen NUMERIC NOT NULL,
  phosphorus NUMERIC NOT NULL,
  potassium NUMERIC NOT NULL,
  report_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE crop_requirements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crop_name TEXT NOT NULL,
  min_n NUMERIC NOT NULL,
  max_n NUMERIC NOT NULL,
  min_p NUMERIC NOT NULL,
  max_p NUMERIC NOT NULL,
  min_k NUMERIC NOT NULL,
  max_k NUMERIC NOT NULL
);

-- Insert dummy reference data
INSERT INTO crop_requirements (crop_name, min_n, max_n, min_p, max_p, min_k, max_k) VALUES
('Wheat', 80, 120, 30, 50, 40, 60),
('Rice', 100, 150, 40, 60, 50, 80),
('Cotton', 120, 160, 50, 70, 60, 90),
('Corn', 140, 180, 60, 80, 70, 100);

-- Insert dummy soil report
INSERT INTO soil_reports (nitrogen, phosphorus, potassium) VALUES (110, 45, 55);

-- Insert dummy cycle and tasks
INSERT INTO crop_cycles (sowing_date, crop_type) VALUES (CURRENT_DATE - 10, 'Wheat');
INSERT INTO daily_tasks (cycle_id, title, status, task_date, task_type) VALUES 
(1, 'Morning Irrigation', 'Pending', CURRENT_DATE, 'Irrigation'),
(1, 'Pest Inspection', 'Pending', CURRENT_DATE, 'Inspection');
