-- Supabase Schema for Market & Post-Harvest Module

CREATE TABLE storage_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crop_type TEXT NOT NULL,
  quantity NUMERIC NOT NULL, -- bags or kg
  unit TEXT NOT NULL DEFAULT 'kg',
  storage_location TEXT NOT NULL,
  entry_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE financial_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_type TEXT NOT NULL, -- 'Income' (Sale) or 'Expense' (Purchase)
  amount NUMERIC NOT NULL,
  category TEXT NOT NULL, -- 'Shopping List', 'Mandi Tracker', 'Other'
  description TEXT,
  transaction_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert Dummy Data for Storage Stock
INSERT INTO storage_stock (crop_type, quantity, unit, storage_location, entry_date) VALUES 
('Wheat', 5000, 'kg', 'Warehouse A', CURRENT_DATE - 5),
('Cotton', 1200, 'kg', 'Silo 2', CURRENT_DATE - 2),
('Rice', 300, 'bags', 'Cold Storage C', CURRENT_DATE);

-- Insert Dummy Data for Financial Ledger
INSERT INTO financial_ledger (transaction_type, amount, category, description, transaction_date) VALUES 
('Expense', 4500.00, 'Shopping List', 'Fertilizer (DAP)', CURRENT_DATE - 10),
('Expense', 1200.00, 'Shopping List', 'Pesticide', CURRENT_DATE - 8),
('Income', 45000.00, 'Mandi Tracker', 'Sold 1000kg Wheat', CURRENT_DATE - 2);
